# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\createacc.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 820)
        Dialog.setMinimumSize(QtCore.QSize(700, 820))
        Dialog.setMaximumSize(QtCore.QSize(700, 820))
        Dialog.setStyleSheet("background-color: rgb(255, 246, 244);\n"
"font: 57 \"Montserrat Medium\";\n"
"")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(260, 60, 181, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/icons/logo.png"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(180, 180, 361, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 163, 134);\n"
"font: 63 16pt \"Montserrat SemiBold\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(210, 570, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 89, 36);\n"
"font: 81 10pt \"Montserrat SemiBold\";")
        self.label_3.setObjectName("label_3")
        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setGeometry(QtCore.QRect(210, 600, 291, 31))
        self.password.setStyleSheet("background-color: rgb(228, 235, 227);\n"
"border-radius: 10px;\n"
"font: 57 7pt \"Montserrat Medium\";\n"
"font-color: rgb(124, 201, 199);\n"
"padding-left: 11px;")
        self.password.setObjectName("password")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(210, 360, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 89, 36);\n"
"font: 81 10pt \"Montserrat SemiBold\";")
        self.label_5.setObjectName("label_5")
        self.lastname = QtWidgets.QLineEdit(Dialog)
        self.lastname.setGeometry(QtCore.QRect(210, 390, 291, 31))
        self.lastname.setStyleSheet("background-color: rgb(228, 235, 227);\n"
"border-radius: 10px;\n"
"font: 57 7pt \"Montserrat Medium\";\n"
"font-color: rgb(124, 201, 199);\n"
"padding-left: 11px;")
        self.lastname.setObjectName("lastname")
        self.firstname = QtWidgets.QLineEdit(Dialog)
        self.firstname.setGeometry(QtCore.QRect(210, 320, 291, 31))
        self.firstname.setStyleSheet("background-color: rgb(228, 235, 227);\n"
"border-radius: 10px;\n"
"font: 57 7pt \"Montserrat Medium\";\n"
"font-color: rgb(124, 201, 199);\n"
"padding-left: 11px;")
        self.firstname.setObjectName("firstname")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(210, 290, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 89, 36);\n"
"font: 81 10pt \"Montserrat SemiBold\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(210, 500, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 89, 36);\n"
"font: 81 10pt \"Montserrat SemiBold\";")
        self.label_7.setObjectName("label_7")
        self.email = QtWidgets.QLineEdit(Dialog)
        self.email.setGeometry(QtCore.QRect(210, 530, 291, 31))
        self.email.setStyleSheet("background-color: rgb(228, 235, 227);\n"
"border-radius: 10px;\n"
"font: 57 7pt \"Montserrat Medium\";\n"
"font-color: rgb(124, 201, 199);\n"
"padding-left: 11px;")
        self.email.setObjectName("email")
        self.clinic = QtWidgets.QLineEdit(Dialog)
        self.clinic.setGeometry(QtCore.QRect(210, 460, 291, 31))
        self.clinic.setStyleSheet("background-color: rgb(228, 235, 227);\n"
"border-radius: 10px;\n"
"font: 57 7pt \"Montserrat Medium\";\n"
"font-color: rgb(124, 201, 199);\n"
"padding-left: 11px;")
        self.clinic.setObjectName("clinic")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(210, 430, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 89, 36);\n"
"font: 81 10pt \"Montserrat SemiBold\";")
        self.label_8.setObjectName("label_8")
        self.confirmpass = QtWidgets.QLineEdit(Dialog)
        self.confirmpass.setGeometry(QtCore.QRect(210, 670, 291, 31))
        self.confirmpass.setStyleSheet("background-color: rgb(228, 235, 227);\n"
"border-radius: 10px;\n"
"font: 57 7pt \"Montserrat Medium\";\n"
"font-color: rgb(124, 201, 199);\n"
"padding-left: 11px;")
        self.confirmpass.setObjectName("confirmpass")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(210, 640, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 89, 36);\n"
"font: 81 10pt \"Montserrat SemiBold\";")
        self.label_4.setObjectName("label_4")
        self.emailinvalid = QtWidgets.QLabel(Dialog)
        self.emailinvalid.setGeometry(QtCore.QRect(210, 260, 291, 21))
        self.emailinvalid.setStyleSheet("font: 57 9pt \"Montserrat SemiBold\";\n"
"color: rgb(220, 26, 0);")
        self.emailinvalid.setAlignment(QtCore.Qt.AlignCenter)
        self.emailinvalid.setObjectName("emailinvalid")
        self.signupbutton = QtWidgets.QPushButton(Dialog)
        self.signupbutton.setGeometry(QtCore.QRect(300, 730, 121, 51))
        self.signupbutton.setStyleSheet("background-color: rgb(255, 163, 134);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"font: 57 10pt \"Montserrat ExtraBold\";")
        self.signupbutton.setObjectName("signupbutton")
        self.failed = QtWidgets.QLabel(Dialog)
        self.failed.setGeometry(QtCore.QRect(210, 260, 291, 21))
        self.failed.setStyleSheet("font: 57 9pt \"Montserrat SemiBold\";\n"
"color: rgb(220, 26, 0);")
        self.failed.setAlignment(QtCore.Qt.AlignCenter)
        self.failed.setObjectName("failed")
        self.password.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.lastname.raise_()
        self.firstname.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.email.raise_()
        self.clinic.raise_()
        self.label_8.raise_()
        self.confirmpass.raise_()
        self.label_4.raise_()
        self.emailinvalid.raise_()
        self.signupbutton.raise_()
        self.failed.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Clinician Sign up"))
        self.label_3.setText(_translate("Dialog", "Password:"))
        self.label_5.setText(_translate("Dialog", "Last Name:"))
        self.label_6.setText(_translate("Dialog", "First Name:"))
        self.label_7.setText(_translate("Dialog", "Email:"))
        self.label_8.setText(_translate("Dialog", "Clinic:"))
        self.label_4.setText(_translate("Dialog", "Confirm Password:"))
        self.emailinvalid.setText(_translate("Dialog", "Email Already In Use"))
        self.signupbutton.setText(_translate("Dialog", "Sign Up"))
        self.failed.setText(_translate("Dialog", "Account Creation Failed"))
import resource_rc
