# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\peach_therapy.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1470, 800)
        MainWindow.setMaximumSize(QtCore.QSize(1470, 800))
        MainWindow.setStyleSheet("background-color: rgb(255, 246, 244);")
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.full_menu_widget = QtWidgets.QWidget(self.centralwidget)
        self.full_menu_widget.setGeometry(QtCore.QRect(10, 0, 350, 800))
        self.full_menu_widget.setMinimumSize(QtCore.QSize(350, 800))
        self.full_menu_widget.setMaximumSize(QtCore.QSize(350, 16777215))
        self.full_menu_widget.setStyleSheet("")
        self.full_menu_widget.setObjectName("full_menu_widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.full_menu_widget)
        self.verticalLayout_6.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_6.setSpacing(15)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget = QtWidgets.QWidget(self.full_menu_widget)
        self.widget.setStyleSheet("background-color: rgb(255, 163, 134);\n"
"border-radius: 10px;")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setMaximumSize(QtCore.QSize(5, 16777215))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.dr_dp = QtWidgets.QLabel(self.widget)
        self.dr_dp.setMinimumSize(QtCore.QSize(90, 90))
        self.dr_dp.setMaximumSize(QtCore.QSize(90, 90))
        self.dr_dp.setStyleSheet("")
        self.dr_dp.setText("")
        self.dr_dp.setPixmap(QtGui.QPixmap(":/icons/icons/logo.png"))
        self.dr_dp.setScaledContents(True)
        self.dr_dp.setObjectName("dr_dp")
        self.horizontalLayout_2.addWidget(self.dr_dp)
        self.dr_info = QtWidgets.QWidget(self.widget)
        self.dr_info.setObjectName("dr_info")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dr_info)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dr_name = QtWidgets.QLabel(self.dr_info)
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(12)
        self.dr_name.setFont(font)
        self.dr_name.setStyleSheet("color: rgb(255, 255, 255);")
        self.dr_name.setObjectName("dr_name")
        self.verticalLayout.addWidget(self.dr_name)
        self.dr_desc = QtWidgets.QLabel(self.dr_info)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(8)
        self.dr_desc.setFont(font)
        self.dr_desc.setStyleSheet("color:rgb(255, 255, 255)")
        self.dr_desc.setObjectName("dr_desc")
        self.verticalLayout.addWidget(self.dr_desc)
        self.horizontalLayout_2.addWidget(self.dr_info)
        self.verticalLayout_6.addWidget(self.widget)
        self.sidebar = QtWidgets.QWidget(self.full_menu_widget)
        self.sidebar.setMinimumSize(QtCore.QSize(0, 0))
        self.sidebar.setMaximumSize(QtCore.QSize(350, 16777215))
        self.sidebar.setStyleSheet("QWidget{\n"
"    background-color: rgb(255, 163, 134);\n"
"    border-top-right-radius: 10px;\n"
"    border-top-left-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: white;\n"
"    text-align: left;\n"
"    padding-left: 30px; \n"
"    border-bottom-right-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    margin-top: 10px;\n"
"    border: none; \n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: white;\n"
"    color: rgb(255, 163, 134);\n"
"    border-top-left-radius: 0px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}")
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.view_btn = QtWidgets.QPushButton(self.sidebar)
        self.view_btn.setMinimumSize(QtCore.QSize(340, 70))
        self.view_btn.setMaximumSize(QtCore.QSize(340, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.view_btn.setFont(font)
        self.view_btn.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/w_view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/p_view.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.view_btn.setIcon(icon)
        self.view_btn.setIconSize(QtCore.QSize(28, 28))
        self.view_btn.setCheckable(True)
        self.view_btn.setAutoExclusive(True)
        self.view_btn.setAutoRepeatDelay(0)
        self.view_btn.setAutoRepeatInterval(0)
        self.view_btn.setObjectName("view_btn")
        self.verticalLayout_3.addWidget(self.view_btn)
        self.add_btn = QtWidgets.QPushButton(self.sidebar)
        self.add_btn.setMinimumSize(QtCore.QSize(340, 70))
        self.add_btn.setMaximumSize(QtCore.QSize(340, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.add_btn.setFont(font)
        self.add_btn.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/w_rec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/p_talk.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.add_btn.setIcon(icon1)
        self.add_btn.setIconSize(QtCore.QSize(36, 30))
        self.add_btn.setCheckable(True)
        self.add_btn.setAutoExclusive(True)
        self.add_btn.setObjectName("add_btn")
        self.verticalLayout_3.addWidget(self.add_btn)
        self.apt_btn = QtWidgets.QPushButton(self.sidebar)
        self.apt_btn.setMinimumSize(QtCore.QSize(340, 70))
        self.apt_btn.setMaximumSize(QtCore.QSize(340, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.apt_btn.setFont(font)
        self.apt_btn.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/w_cal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/p_cal.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.apt_btn.setIcon(icon2)
        self.apt_btn.setIconSize(QtCore.QSize(28, 28))
        self.apt_btn.setCheckable(True)
        self.apt_btn.setAutoExclusive(True)
        self.apt_btn.setObjectName("apt_btn")
        self.verticalLayout_3.addWidget(self.apt_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 245, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.settings_btn = QtWidgets.QPushButton(self.sidebar)
        self.settings_btn.setMinimumSize(QtCore.QSize(340, 70))
        self.settings_btn.setMaximumSize(QtCore.QSize(340, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.settings_btn.setFont(font)
        self.settings_btn.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/w_gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/p_gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.settings_btn.setIcon(icon3)
        self.settings_btn.setIconSize(QtCore.QSize(28, 28))
        self.settings_btn.setCheckable(True)
        self.settings_btn.setAutoExclusive(True)
        self.settings_btn.setObjectName("settings_btn")
        self.verticalLayout_3.addWidget(self.settings_btn)
        self.exit_btn = QtWidgets.QPushButton(self.sidebar)
        self.exit_btn.setMinimumSize(QtCore.QSize(340, 70))
        self.exit_btn.setMaximumSize(QtCore.QSize(340, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.exit_btn.setFont(font)
        self.exit_btn.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/w_logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/p_logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.exit_btn.setIcon(icon4)
        self.exit_btn.setIconSize(QtCore.QSize(28, 28))
        self.exit_btn.setCheckable(True)
        self.exit_btn.setAutoExclusive(True)
        self.exit_btn.setObjectName("exit_btn")
        self.verticalLayout_3.addWidget(self.exit_btn)
        self.verticalLayout_6.addWidget(self.sidebar)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(360, 0, 1100, 800))
        self.widget_3.setMinimumSize(QtCore.QSize(1100, 800))
        self.widget_3.setMaximumSize(QtCore.QSize(1100, 800))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.menuWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.menuWidget.setObjectName("menuWidget")
        self.view_pg_2 = QtWidgets.QWidget()
        self.view_pg_2.setObjectName("view_pg_2")
        self.widget_2 = QtWidgets.QWidget(self.view_pg_2)
        self.widget_2.setGeometry(QtCore.QRect(10, 20, 1051, 751))
        self.widget_2.setObjectName("widget_2")
        self.viewWidget = QtWidgets.QStackedWidget(self.widget_2)
        self.viewWidget.setGeometry(QtCore.QRect(-10, 10, 1061, 721))
        self.viewWidget.setStyleSheet("")
        self.viewWidget.setObjectName("viewWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.patient_profile_layout = QtWidgets.QScrollArea(self.page)
        self.patient_profile_layout.setGeometry(QtCore.QRect(30, 70, 991, 641))
        self.patient_profile_layout.setMinimumSize(QtCore.QSize(250, 0))
        self.patient_profile_layout.setStyleSheet("QWidget {\n"
"    border: none;\n"
"    margin-bottom: 20px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(255, 163, 134);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(229, 226, 218);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(229, 226, 218);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(255, 163, 134);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(255, 163, 134);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(255, 163, 134);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}")
        self.patient_profile_layout.setWidgetResizable(True)
        self.patient_profile_layout.setObjectName("patient_profile_layout")
        self.scroll_patients = QtWidgets.QWidget()
        self.scroll_patients.setGeometry(QtCore.QRect(0, 0, 951, 601))
        self.scroll_patients.setObjectName("scroll_patients")
        self.profilecard = QtWidgets.QWidget(self.scroll_patients)
        self.profilecard.setGeometry(QtCore.QRect(10, 10, 230, 270))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profilecard.sizePolicy().hasHeightForWidth())
        self.profilecard.setSizePolicy(sizePolicy)
        self.profilecard.setMinimumSize(QtCore.QSize(230, 270))
        self.profilecard.setMaximumSize(QtCore.QSize(230, 270))
        self.profilecard.setStyleSheet("background-color: rgb(255, 188, 167);\n"
"border-radius: 10px;\n"
"padding-bottom: 20px;")
        self.profilecard.setObjectName("profilecard")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.profilecard)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.dr_dp_4 = QtWidgets.QLabel(self.profilecard)
        self.dr_dp_4.setMinimumSize(QtCore.QSize(180, 150))
        self.dr_dp_4.setMaximumSize(QtCore.QSize(230, 180))
        self.dr_dp_4.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dr_dp_4.setFont(font)
        self.dr_dp_4.setStyleSheet("")
        self.dr_dp_4.setText("")
        self.dr_dp_4.setPixmap(QtGui.QPixmap(":/icons/icons/logo.png"))
        self.dr_dp_4.setScaledContents(False)
        self.dr_dp_4.setAlignment(QtCore.Qt.AlignCenter)
        self.dr_dp_4.setWordWrap(False)
        self.dr_dp_4.setObjectName("dr_dp_4")
        self.verticalLayout_5.addWidget(self.dr_dp_4)
        self.name_btn = QtWidgets.QPushButton(self.profilecard)
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.name_btn.setFont(font)
        self.name_btn.setStyleSheet("\n"
"color: rgb(255, 245, 243);")
        self.name_btn.setObjectName("name_btn")
        self.verticalLayout_5.addWidget(self.name_btn)
        self.nopatients = QtWidgets.QLabel(self.scroll_patients)
        self.nopatients.setGeometry(QtCore.QRect(280, 290, 481, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.nopatients.setFont(font)
        self.nopatients.setStyleSheet("color: rgb(255, 163, 134);\n"
"font: 63 16pt \"Montserrat SemiBold\";")
        self.nopatients.setAlignment(QtCore.Qt.AlignCenter)
        self.nopatients.setObjectName("nopatients")
        self.patient_profile_layout.setWidget(self.scroll_patients)
        self.profiles_title = QtWidgets.QLabel(self.page)
        self.profiles_title.setGeometry(QtCore.QRect(260, 0, 591, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.profiles_title.setFont(font)
        self.profiles_title.setStyleSheet("color: rgb(255, 163, 134);\n"
"font: 63 16pt \"Montserrat SemiBold\";")
        self.profiles_title.setAlignment(QtCore.Qt.AlignCenter)
        self.profiles_title.setObjectName("profiles_title")
        self.viewWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.overview_title = QtWidgets.QLabel(self.page_2)
        self.overview_title.setGeometry(QtCore.QRect(330, 20, 391, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.overview_title.setFont(font)
        self.overview_title.setStyleSheet("color: rgb(255, 163, 134);\n"
"font: 63 16pt \"Montserrat SemiBold\";")
        self.overview_title.setAlignment(QtCore.Qt.AlignCenter)
        self.overview_title.setObjectName("overview_title")
        self.backtoprof_btn = QtWidgets.QPushButton(self.page_2)
        self.backtoprof_btn.setGeometry(QtCore.QRect(840, 670, 181, 51))
        self.backtoprof_btn.setStyleSheet("color: rgb(255, 163, 134);\n"
"background-color: rgb(229, 226, 218);\n"
"border-radius: 10px;\n"
"font: 57 10pt \"Montserrat ExtraBold\";")
        self.backtoprof_btn.setObjectName("backtoprof_btn")
        self.viewrec_btn = QtWidgets.QPushButton(self.page_2)
        self.viewrec_btn.setGeometry(QtCore.QRect(90, 570, 261, 51))
        self.viewrec_btn.setStyleSheet("background-color: rgb(208, 233, 236);\n"
"color: rgb(124, 201, 199);\n"
"border-radius: 10px;\n"
"font: 57 10pt \"Montserrat ExtraBold\";")
        self.viewrec_btn.setObjectName("viewrec_btn")
        self.addrec_btn = QtWidgets.QPushButton(self.page_2)
        self.addrec_btn.setGeometry(QtCore.QRect(110, 640, 221, 51))
        self.addrec_btn.setStyleSheet("background-color: rgb(255, 163, 134);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"font: 57 10pt \"Montserrat ExtraBold\";")
        self.addrec_btn.setObjectName("addrec_btn")
        self.label_40 = QtWidgets.QLabel(self.page_2)
        self.label_40.setGeometry(QtCore.QRect(70, 520, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("color: rgb(102, 75, 66);")
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 200, 311, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.progress_gph = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.progress_gph.setContentsMargins(0, 0, 0, 0)
        self.progress_gph.setObjectName("progress_gph")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.page_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(380, 190, 681, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.bar_gph = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.bar_gph.setContentsMargins(0, 0, 0, 0)
        self.bar_gph.setObjectName("bar_gph")
        self.label_41 = QtWidgets.QLabel(self.page_2)
        self.label_41.setGeometry(QtCore.QRect(70, 160, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("color: rgb(102, 75, 66);")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.page_2)
        self.label_42.setGeometry(QtCore.QRect(550, 160, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("color: rgb(102, 75, 66);")
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.page_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(370, 430, 701, 241))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.boundary_gph = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.boundary_gph.setContentsMargins(0, 0, 0, 0)
        self.boundary_gph.setObjectName("boundary_gph")
        self.widget_4 = QtWidgets.QWidget(self.page_2)
        self.widget_4.setGeometry(QtCore.QRect(80, 100, 961, 41))
        self.widget_4.setStyleSheet("background-color: rgb(208, 233, 236);\n"
"padding-left: 10px")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.name_ov = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.name_ov.setFont(font)
        self.name_ov.setStyleSheet("color: rgb(102, 75, 66);\n"
"")
        self.name_ov.setObjectName("name_ov")
        self.horizontalLayout_4.addWidget(self.name_ov)
        self.birthday_ov = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.birthday_ov.setFont(font)
        self.birthday_ov.setStyleSheet("color: rgb(102, 75, 66);")
        self.birthday_ov.setObjectName("birthday_ov")
        self.horizontalLayout_4.addWidget(self.birthday_ov)
        self.sex_ov = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.sex_ov.setFont(font)
        self.sex_ov.setStyleSheet("color: rgb(102, 75, 66);")
        self.sex_ov.setObjectName("sex_ov")
        self.horizontalLayout_4.addWidget(self.sex_ov)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.label_46 = QtWidgets.QLabel(self.page_2)
        self.label_46.setGeometry(QtCore.QRect(550, 410, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("color: rgb(102, 75, 66);")
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.overview_title.raise_()
        self.viewrec_btn.raise_()
        self.addrec_btn.raise_()
        self.label_40.raise_()
        self.verticalLayoutWidget.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.label_41.raise_()
        self.label_42.raise_()
        self.verticalLayoutWidget_3.raise_()
        self.widget_4.raise_()
        self.label_46.raise_()
        self.backtoprof_btn.raise_()
        self.viewWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.rec_title = QtWidgets.QLabel(self.page_3)
        self.rec_title.setGeometry(QtCore.QRect(350, 20, 391, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.rec_title.setFont(font)
        self.rec_title.setStyleSheet("color: rgb(255, 163, 134);\n"
"font: 63 16pt \"Montserrat SemiBold\";")
        self.rec_title.setAlignment(QtCore.Qt.AlignCenter)
        self.rec_title.setObjectName("rec_title")
        self.backtoprof_btn_2 = QtWidgets.QPushButton(self.page_3)
        self.backtoprof_btn_2.setGeometry(QtCore.QRect(840, 670, 181, 51))
        self.backtoprof_btn_2.setStyleSheet("color: rgb(255, 163, 134);\n"
"background-color: rgb(229, 226, 218);\n"
"border-radius: 10px;\n"
"font: 57 10pt \"Montserrat ExtraBold\";")
        self.backtoprof_btn_2.setObjectName("backtoprof_btn_2")
        self.rec_layout = QtWidgets.QScrollArea(self.page_3)
        self.rec_layout.setGeometry(QtCore.QRect(60, 100, 980, 541))
        self.rec_layout.setMaximumSize(QtCore.QSize(980, 549))
        self.rec_layout.setStyleSheet("border: none;")
        self.rec_layout.setWidgetResizable(True)
        self.rec_layout.setObjectName("rec_layout")
        self.rec_scroll = QtWidgets.QWidget()
        self.rec_scroll.setGeometry(QtCore.QRect(0, 0, 980, 541))
        self.rec_scroll.setObjectName("rec_scroll")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.rec_scroll)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.rec_layout.setWidget(self.rec_scroll)
        self.loadingrec = QtWidgets.QLabel(self.page_3)
        self.loadingrec.setGeometry(QtCore.QRect(360, 340, 391, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.loadingrec.setFont(font)
        self.loadingrec.setStyleSheet("color: rgb(124, 201, 199);\n"
"font: 63 16pt \"Montserrat SemiBold\";")
        self.loadingrec.setAlignment(QtCore.Qt.AlignCenter)
        self.loadingrec.setObjectName("loadingrec")
        self.norec = QtWidgets.QLabel(self.page_3)
        self.norec.setGeometry(QtCore.QRect(320, 340, 481, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.norec.setFont(font)
        self.norec.setStyleSheet("color: rgb(255, 163, 134);\n"
"font: 63 16pt \"Montserrat SemiBold\";")
        self.norec.setAlignment(QtCore.Qt.AlignCenter)
        self.norec.setObjectName("norec")
        self.viewWidget.addWidget(self.page_3)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.Title_10 = QtWidgets.QLabel(self.page_7)
        self.Title_10.setGeometry(QtCore.QRect(310, 20, 481, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.Title_10.setFont(font)
        self.Title_10.setStyleSheet("color: rgb(255, 163, 134);\n"
"font: 63 16pt \"Montserrat SemiBold\";")
        self.Title_10.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_10.setObjectName("Title_10")
        self.startrec_btn = QtWidgets.QPushButton(self.page_7)
        self.startrec_btn.setGeometry(QtCore.QRect(100, 130, 220, 60))
        self.startrec_btn.setMinimumSize(QtCore.QSize(220, 60))
        self.startrec_btn.setMaximumSize(QtCore.QSize(340, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.startrec_btn.setFont(font)
        self.startrec_btn.setStyleSheet("background-color: rgb(124, 201, 199);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"font: 57 9pt \"Montserrat ExtraBold\";\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/start rec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/start rec.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.startrec_btn.setIcon(icon5)
        self.startrec_btn.setIconSize(QtCore.QSize(22, 22))
        self.startrec_btn.setCheckable(True)
        self.startrec_btn.setAutoExclusive(True)
        self.startrec_btn.setAutoRepeatDelay(0)
        self.startrec_btn.setAutoRepeatInterval(0)
        self.startrec_btn.setObjectName("startrec_btn")
        self.stoprec_btn = QtWidgets.QPushButton(self.page_7)
        self.stoprec_btn.setGeometry(QtCore.QRect(100, 220, 220, 60))
        self.stoprec_btn.setMinimumSize(QtCore.QSize(220, 60))
        self.stoprec_btn.setMaximumSize(QtCore.QSize(340, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.stoprec_btn.setFont(font)
        self.stoprec_btn.setStyleSheet("background-color: rgb(124, 201, 199);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"font: 57 9pt \"Montserrat ExtraBold\";\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/stoprec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/stoprec.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.stoprec_btn.setIcon(icon6)
        self.stoprec_btn.setIconSize(QtCore.QSize(24, 24))
        self.stoprec_btn.setCheckable(True)
        self.stoprec_btn.setAutoExclusive(True)
        self.stoprec_btn.setAutoRepeatDelay(0)
        self.stoprec_btn.setAutoRepeatInterval(0)
        self.stoprec_btn.setObjectName("stoprec_btn")
        self.playback_btn = QtWidgets.QPushButton(self.page_7)
        self.playback_btn.setGeometry(QtCore.QRect(100, 310, 220, 60))
        self.playback_btn.setMinimumSize(QtCore.QSize(220, 60))
        self.playback_btn.setMaximumSize(QtCore.QSize(340, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.playback_btn.setFont(font)
        self.playback_btn.setStyleSheet("background-color: rgb(229, 226, 218);\n"
"color: rgb(255, 163, 134);\n"
"border-radius: 10px;\n"
"font: 57 9pt \"Montserrat ExtraBold\";\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/p_playback.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/p_playback.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.playback_btn.setIcon(icon7)
        self.playback_btn.setIconSize(QtCore.QSize(29, 28))
        self.playback_btn.setCheckable(True)
        self.playback_btn.setAutoExclusive(True)
        self.playback_btn.setAutoRepeatDelay(0)
        self.playback_btn.setAutoRepeatInterval(0)
        self.playback_btn.setObjectName("playback_btn")
        self.redo_btn = QtWidgets.QPushButton(self.page_7)
        self.redo_btn.setGeometry(QtCore.QRect(100, 400, 220, 60))
        self.redo_btn.setMinimumSize(QtCore.QSize(220, 60))
        self.redo_btn.setMaximumSize(QtCore.QSize(340, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.redo_btn.setFont(font)
        self.redo_btn.setStyleSheet("background-color: rgb(229, 226, 218);\n"
"color: rgb(255, 163, 134);\n"
"border-radius: 10px;\n"
"font: 57 9pt \"Montserrat ExtraBold\";\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/p_redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/p_redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.redo_btn.setIcon(icon8)
        self.redo_btn.setIconSize(QtCore.QSize(23, 28))
        self.redo_btn.setCheckable(True)
        self.redo_btn.setAutoExclusive(True)
        self.redo_btn.setAutoRepeatDelay(0)
        self.redo_btn.setAutoRepeatInterval(0)
        self.redo_btn.setObjectName("redo_btn")
        self.save_btn = QtWidgets.QPushButton(self.page_7)
        self.save_btn.setGeometry(QtCore.QRect(100, 490, 220, 60))
        self.save_btn.setMinimumSize(QtCore.QSize(220, 60))
        self.save_btn.setMaximumSize(QtCore.QSize(340, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.save_btn.setFont(font)
        self.save_btn.setStyleSheet("background-color: rgb(255, 163, 134);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"font: 57 9pt \"Montserrat ExtraBold\";\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.save_btn.setIcon(icon9)
        self.save_btn.setIconSize(QtCore.QSize(24, 24))
        self.save_btn.setCheckable(True)
        self.save_btn.setAutoExclusive(True)
        self.save_btn.setAutoRepeatDelay(0)
        self.save_btn.setAutoRepeatInterval(0)
        self.save_btn.setObjectName("save_btn")
        self.widget_7 = QtWidgets.QWidget(self.page_7)
        self.widget_7.setGeometry(QtCore.QRect(390, 160, 581, 41))
        self.widget_7.setStyleSheet("background-color: rgb(208, 233, 236);\n"
"padding-left: 10px")
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.rec_patient = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rec_patient.setFont(font)
        self.rec_patient.setStyleSheet("color: rgb(102, 75, 66);")
        self.rec_patient.setObjectName("rec_patient")
        self.verticalLayout_7.addWidget(self.rec_patient)
        self.label_43 = QtWidgets.QLabel(self.page_7)
        self.label_43.setGeometry(QtCore.QRect(390, 210, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("color: rgb(255, 89, 36);\n"
"font: 81 10pt \"Montserrat SemiBold\";")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.page_7)
        self.label_44.setGeometry(QtCore.QRect(390, 130, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("color: rgb(255, 89, 36);\n"
"font: 81 10pt \"Montserrat SemiBold\";")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.page_7)
        self.label_45.setGeometry(QtCore.QRect(390, 360, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("color: rgb(255, 89, 36);\n"
"font: 81 10pt \"Montserrat SemiBold\";")
        self.label_45.setObjectName("label_45")
        self.widget_8 = QtWidgets.QWidget(self.page_7)
        self.widget_8.setGeometry(QtCore.QRect(390, 240, 581, 41))
        self.widget_8.setStyleSheet("background-color: rgb(208, 233, 236);\n"
"padding-left: 10px")
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.rec_date = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rec_date.setFont(font)
        self.rec_date.setStyleSheet("color: rgb(102, 75, 66);")
        self.rec_date.setObjectName("rec_date")
        self.verticalLayout_8.addWidget(self.rec_date)
        self.label_16 = QtWidgets.QLabel(self.page_7)
        self.label_16.setGeometry(QtCore.QRect(390, 290, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255, 89, 36);\n"
"font: 81 10pt \"Montserrat SemiBold\";")
        self.label_16.setObjectName("label_16")
        self.recphrase = QtWidgets.QLineEdit(self.page_7)
        self.recphrase.setGeometry(QtCore.QRect(390, 320, 581, 31))
        self.recphrase.setStyleSheet("background-color: rgb(228, 235, 227);\n"
"border-radius: 10px;\n"
"font: 57 9pt \"Montserrat Medium\";\n"
"padding-left: 11px;")
        self.recphrase.setObjectName("recphrase")
        self.viewrec_btn_2 = QtWidgets.QPushButton(self.page_7)
        self.viewrec_btn_2.setGeometry(QtCore.QRect(550, 630, 281, 51))
        self.viewrec_btn_2.setStyleSheet("background-color: rgb(208, 233, 236);\n"
"color: rgb(124, 201, 199);\n"
"border-radius: 10px;\n"
"font: 57 10pt \"Montserrat ExtraBold\";")
        self.viewrec_btn_2.setObjectName("viewrec_btn_2")
        self.savesuccess = QtWidgets.QLabel(self.page_7)
        self.savesuccess.setGeometry(QtCore.QRect(70, 590, 291, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.savesuccess.setFont(font)
        self.savesuccess.setStyleSheet("font: 57 10pt \"Montserrat SemiBold\";\n"
"color: rgb(36, 168, 172);")
        self.savesuccess.setAlignment(QtCore.Qt.AlignCenter)
        self.savesuccess.setObjectName("savesuccess")
        self.savefail = QtWidgets.QLabel(self.page_7)
        self.savefail.setGeometry(QtCore.QRect(70, 620, 291, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.savefail.setFont(font)
        self.savefail.setStyleSheet("font: 57 10pt \"Montserrat SemiBold\";\n"
"color: rgb(220, 26, 0);")
        self.savefail.setAlignment(QtCore.Qt.AlignCenter)
        self.savefail.setObjectName("savefail")
        self.loading = QtWidgets.QLabel(self.page_7)
        self.loading.setGeometry(QtCore.QRect(60, 560, 291, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.loading.setFont(font)
        self.loading.setStyleSheet("font: 57 10pt \"Montserrat SemiBold\";\n"
"color: rgb(36, 168, 172);")
        self.loading.setAlignment(QtCore.Qt.AlignCenter)
        self.loading.setObjectName("loading")
        self.recnotes = QtWidgets.QTextEdit(self.page_7)
        self.recnotes.setGeometry(QtCore.QRect(390, 390, 581, 221))
        self.recnotes.setStyleSheet("QTextEdit {\n"
"    background-color: rgb(228, 235, 227);\n"
"    border-radius: 10px;\n"
"    font: 57 9pt \"Montserrat Medium\";\n"
"    padding-left: 11px;\n"
"    padding-top: 5px;\n"
"}\n"
"\n"
"/* Set styling for the vertical scrollbar */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"/* Set styling for the handle bar */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(255, 163, 134);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {    \n"
"    background-color: rgb(229, 226, 218);\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(229, 226, 218);\n"
"}\n"
"\n"
"/* Set styling for the top button */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(255, 163, 134);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(255, 163, 134);\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* Set styling for the bottom button */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(255, 163, 134);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"")
        self.recnotes.setObjectName("recnotes")
        self.viewWidget.addWidget(self.page_7)
        self.menuWidget.addWidget(self.view_pg_2)
        self.add_pg = QtWidgets.QWidget()
        self.add_pg.setObjectName("add_pg")
        self.lastname_patient = QtWidgets.QLineEdit(self.add_pg)
        self.lastname_patient.setGeometry(QtCore.QRect(370, 300, 381, 31))
        self.lastname_patient.setStyleSheet("background-color: rgb(228, 235, 227);\n"
"border-radius: 10px;\n"
"font: 57 9pt \"Montserrat Medium\";\n"
"padding-left: 11px;")
        self.lastname_patient.setObjectName("lastname_patient")
        self.label_6 = QtWidgets.QLabel(self.add_pg)
        self.label_6.setGeometry(QtCore.QRect(370, 200, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 89, 36);\n"
"font: 81 10pt \"Montserrat SemiBold\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.add_pg)
        self.label_7.setGeometry(QtCore.QRect(370, 480, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 89, 36);\n"
"font: 81 10pt \"Montserrat SemiBold\";")
        self.label_7.setObjectName("label_7")
        self.firstname_patient = QtWidgets.QLineEdit(self.add_pg)
        self.firstname_patient.setGeometry(QtCore.QRect(370, 230, 381, 31))
        self.firstname_patient.setStyleSheet("background-color: rgb(228, 235, 227);\n"
"border-radius: 10px;\n"
"font: 57 9pt \"Montserrat Medium\";\n"
"padding-left: 11px;")
        self.firstname_patient.setObjectName("firstname_patient")
        self.label_3 = QtWidgets.QLabel(self.add_pg)
        self.label_3.setGeometry(QtCore.QRect(370, 550, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 89, 36);\n"
"font: 81 10pt \"Montserrat SemiBold\";")
        self.label_3.setObjectName("label_3")
        self.email_patient = QtWidgets.QLineEdit(self.add_pg)
        self.email_patient.setGeometry(QtCore.QRect(370, 510, 381, 31))
        self.email_patient.setStyleSheet("background-color: rgb(228, 235, 227);\n"
"border-radius: 10px;\n"
"font: 57 9pt \"Montserrat Medium\";\n"
"padding-left: 11px;")
        self.email_patient.setObjectName("email_patient")
        self.label_8 = QtWidgets.QLabel(self.add_pg)
        self.label_8.setGeometry(QtCore.QRect(370, 340, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 89, 36);\n"
"font: 81 10pt \"Montserrat SemiBold\";")
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(self.add_pg)
        self.label_5.setGeometry(QtCore.QRect(370, 270, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 89, 36);\n"
"font: 81 10pt \"Montserrat SemiBold\";")
        self.label_5.setObjectName("label_5")
        self.createprofile = QtWidgets.QPushButton(self.add_pg)
        self.createprofile.setGeometry(QtCore.QRect(480, 640, 171, 51))
        self.createprofile.setStyleSheet("background-color: rgb(255, 163, 134);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"font: 57 10pt \"Montserrat ExtraBold\";")
        self.createprofile.setObjectName("createprofile")
        self.Title = QtWidgets.QLabel(self.add_pg)
        self.Title.setGeometry(QtCore.QRect(360, 70, 391, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.Title.setFont(font)
        self.Title.setStyleSheet("color: rgb(255, 163, 134);\n"
"font: 63 16pt \"Montserrat SemiBold\";")
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.label_15 = QtWidgets.QLabel(self.add_pg)
        self.label_15.setGeometry(QtCore.QRect(370, 410, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 89, 36);\n"
"font: 81 10pt \"Montserrat SemiBold\";")
        self.label_15.setObjectName("label_15")
        self.profilesuccess = QtWidgets.QLabel(self.add_pg)
        self.profilesuccess.setGeometry(QtCore.QRect(420, 140, 291, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.profilesuccess.setFont(font)
        self.profilesuccess.setStyleSheet("font: 57 10pt \"Montserrat SemiBold\";\n"
"color: rgb(36, 168, 172);")
        self.profilesuccess.setAlignment(QtCore.Qt.AlignCenter)
        self.profilesuccess.setObjectName("profilesuccess")
        self.birthday = QtWidgets.QDateEdit(self.add_pg)
        self.birthday.setGeometry(QtCore.QRect(370, 370, 381, 31))
        self.birthday.setStyleSheet("\n"
"QDateEdit {\n"
"    background-color: rgb(228, 235, 227);\n"
"    border-radius: 10px;\n"
"    font: 57 9pt \"Montserrat Medium\";\n"
"    padding-left: 11px;\n"
"    border: none;\n"
"}\n"
"\n"
"QDateEdit::up-button, QDateEdit::down-button {\n"
"    border: none;\n"
"    width: 25px\n"
"}\n"
"\n"
"QDateEdit::up-button {\n"
"    subcontrol-position: top right;\n"
"    \n"
"}\n"
"\n"
"QDateEdit::down-button {\n"
"    subcontrol-position: bottom right;\n"
"    \n"
"}\n"
"\n"
"QDateEdit::up-arrow, QDateEdit::down-arrow {\n"
"    border: 5px solid rgba(255, 255, 255, 0);\n"
"    width: 0;\n"
"    height: 0;\n"
"\n"
"}\n"
"\n"
"QDateEdit::up-arrow {\n"
"    border-top: none;\n"
"    border-bottom-color: rgb(255, 163, 134);\n"
"    \n"
"}\n"
"\n"
"QDateEdit::down-arrow {\n"
"    border-bottom: none;\n"
"    border-top-color: rgb(255, 163, 134);\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QDateEdit::up-button:hover, QDateEdit::down-button:hover {\n"
"    background-color: rgb(229, 226, 218); /* Change the background color on hover */\n"
"}\n"
"\n"
"QDateEdit::up-button:hover {\n"
"    border-top-right-radius: 10px; /* Change the background color on hover */\n"
"}\n"
"\n"
"QDateEdit::down-button:hover {\n"
"    border-bottom-right-radius: 10px; /* Change the background color on hover */\n"
"}\n"
"\n"
"\n"
"")
        self.birthday.setObjectName("birthday")
        self.sexdropdown = QtWidgets.QComboBox(self.add_pg)
        self.sexdropdown.setGeometry(QtCore.QRect(370, 440, 381, 31))
        self.sexdropdown.setStyleSheet("/* QComboBox */\n"
"QComboBox {\n"
"    background-color: rgb(228, 235, 227);\n"
"    border-radius: 10px;\n"
"    font: 57 9pt \"Montserrat Medium\";\n"
"    padding-left: 11px;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 25px;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    border: 5px solid rgba(255, 255, 255, 0);\n"
"    width: 0;\n"
"    height: 0;\n"
"    border-bottom: none;\n"
"    border-top-color: rgb(255, 163, 134);\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QComboBox::drop-down:hover {\n"
"    background-color: rgb(229, 226, 218);\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"")
        self.sexdropdown.setObjectName("sexdropdown")
        self.sexdropdown.addItem("")
        self.sexdropdown.addItem("")
        self.failed_patient = QtWidgets.QLabel(self.add_pg)
        self.failed_patient.setGeometry(QtCore.QRect(420, 170, 291, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.failed_patient.setFont(font)
        self.failed_patient.setStyleSheet("font: 57 10pt \"Montserrat SemiBold\";\n"
"color: rgb(220, 26, 0);")
        self.failed_patient.setAlignment(QtCore.Qt.AlignCenter)
        self.failed_patient.setObjectName("failed_patient")
        self.label_2 = QtWidgets.QLabel(self.add_pg)
        self.label_2.setGeometry(QtCore.QRect(370, 580, 381, 31))
        self.label_2.setStyleSheet("background-color: rgb(207, 226, 218);\n"
"border-radius: 10px;\n"
"font: 57 9pt \"Montserrat Medium\";\n"
"padding-left: 11px;")
        self.label_2.setObjectName("label_2")
        self.menuWidget.addWidget(self.add_pg)
        self.apts_pg = QtWidgets.QWidget()
        self.apts_pg.setObjectName("apts_pg")
        self.calendar = QtWidgets.QCalendarWidget(self.apts_pg)
        self.calendar.setGeometry(QtCore.QRect(80, 50, 441, 341))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.calendar.setFont(font)
        self.calendar.setStyleSheet("background-color: rgb(229, 226, 218);\n"
"color: rgb(102, 75, 66);")
        self.calendar.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendar.setGridVisible(False)
        self.calendar.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendar.setNavigationBarVisible(True)
        self.calendar.setDateEditEnabled(True)
        self.calendar.setObjectName("calendar")
        self.label_17 = QtWidgets.QLabel(self.apts_pg)
        self.label_17.setGeometry(QtCore.QRect(400, 430, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(102, 75, 66);")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.apttable = QtWidgets.QTableWidget(self.apts_pg)
        self.apttable.setGeometry(QtCore.QRect(30, 480, 1021, 271))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.apttable.setFont(font)
        self.apttable.setStyleSheet("font: 57 9pt \"Montserrat Medium\";\n"
"border: none; \n"
"background-color: rgb(208, 233, 236);")
        self.apttable.setObjectName("apttable")
        self.apttable.setColumnCount(4)
        self.apttable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.apttable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.apttable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.apttable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.apttable.setHorizontalHeaderItem(3, item)
        self.label_21 = QtWidgets.QLabel(self.apts_pg)
        self.label_21.setGeometry(QtCore.QRect(670, 50, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(102, 75, 66);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_37 = QtWidgets.QLabel(self.apts_pg)
        self.label_37.setGeometry(QtCore.QRect(600, 210, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color: rgb(255, 89, 36);\n"
"font: 81 10pt \"Montserrat SemiBold\";")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.apts_pg)
        self.label_38.setGeometry(QtCore.QRect(600, 140, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("color: rgb(255, 89, 36);\n"
"font: 81 10pt \"Montserrat SemiBold\";")
        self.label_38.setObjectName("label_38")
        self.aptdatesel = QtWidgets.QDateTimeEdit(self.apts_pg)
        self.aptdatesel.setGeometry(QtCore.QRect(600, 240, 431, 31))
        self.aptdatesel.setStyleSheet("/* QDateTimeEdit */\n"
"QDateTimeEdit {\n"
"    background-color: rgb(228, 235, 227);\n"
"    border-radius: 10px;\n"
"    font: 57 9pt \"Montserrat Medium\";\n"
"    padding-left: 11px;\n"
"    border: none;\n"
"}\n"
"\n"
"QDateTimeEdit::up-button, QDateTimeEdit::down-button {\n"
"    border: none;\n"
"    width: 25px;\n"
"}\n"
"\n"
"QDateTimeEdit::up-button {\n"
"    subcontrol-position: top right;\n"
"}\n"
"\n"
"QDateTimeEdit::down-button {\n"
"    subcontrol-position: bottom right;\n"
"}\n"
"\n"
"QDateTimeEdit::up-arrow, QDateTimeEdit::down-arrow {\n"
"    border: 5px solid rgba(255, 255, 255, 0);\n"
"    width: 0;\n"
"    height: 0;\n"
"}\n"
"\n"
"QDateTimeEdit::up-arrow {\n"
"    border-top: none;\n"
"    border-bottom-color: rgb(255, 163, 134);\n"
"}\n"
"\n"
"QDateTimeEdit::down-arrow {\n"
"    border-bottom: none;\n"
"    border-top-color: rgb(255, 163, 134);\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QDateTimeEdit::up-button:hover, QDateTimeEdit::down-button:hover {\n"
"    background-color: rgb(229, 226, 218); /* Change the background color on hover */\n"
"}\n"
"\n"
"QDateTimeEdit::up-button:hover {\n"
"    border-top-right-radius: 10px; /* Change the background color on hover */\n"
"}\n"
"\n"
"QDateTimeEdit::down-button:hover {\n"
"    border-bottom-right-radius: 10px; /* Change the background color on hover */\n"
"}\n"
"")
        self.aptdatesel.setObjectName("aptdatesel")
        self.patientdropdown = QtWidgets.QComboBox(self.apts_pg)
        self.patientdropdown.setGeometry(QtCore.QRect(600, 170, 431, 31))
        self.patientdropdown.setStyleSheet("/* QComboBox */\n"
"QComboBox {\n"
"    background-color: rgb(228, 235, 227);\n"
"    border-radius: 10px;\n"
"    font: 57 9pt \"Montserrat Medium\";\n"
"    padding-left: 11px;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 25px;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    border: 5px solid rgba(255, 255, 255, 0);\n"
"    width: 0;\n"
"    height: 0;\n"
"    border-bottom: none;\n"
"    border-top-color: rgb(255, 163, 134);\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QComboBox::drop-down:hover {\n"
"    background-color: rgb(229, 226, 218);\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"")
        self.patientdropdown.setObjectName("patientdropdown")
        self.patientdropdown.addItem("")
        self.booknow_btn = QtWidgets.QPushButton(self.apts_pg)
        self.booknow_btn.setGeometry(QtCore.QRect(730, 370, 171, 51))
        self.booknow_btn.setStyleSheet("background-color: rgb(255, 163, 134);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"font: 57 10pt \"Montserrat ExtraBold\";")
        self.booknow_btn.setObjectName("booknow_btn")
        self.label_39 = QtWidgets.QLabel(self.apts_pg)
        self.label_39.setGeometry(QtCore.QRect(600, 280, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color: rgb(255, 89, 36);\n"
"font: 81 10pt \"Montserrat SemiBold\";")
        self.label_39.setObjectName("label_39")
        self.aptnote = QtWidgets.QLineEdit(self.apts_pg)
        self.aptnote.setGeometry(QtCore.QRect(600, 310, 431, 31))
        self.aptnote.setStyleSheet("background-color: rgb(228, 235, 227);\n"
"border-radius: 10px;\n"
"font: 57 9pt \"Montserrat Medium\";\n"
"padding-left: 11px;")
        self.aptnote.setObjectName("aptnote")
        self.aptsuccess = QtWidgets.QLabel(self.apts_pg)
        self.aptsuccess.setGeometry(QtCore.QRect(600, 100, 431, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.aptsuccess.setFont(font)
        self.aptsuccess.setStyleSheet("font: 57 10pt \"Montserrat SemiBold\";\n"
"color: rgb(36, 168, 172);")
        self.aptsuccess.setAlignment(QtCore.Qt.AlignCenter)
        self.aptsuccess.setObjectName("aptsuccess")
        self.selpatienterror = QtWidgets.QLabel(self.apts_pg)
        self.selpatienterror.setGeometry(QtCore.QRect(600, 100, 431, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.selpatienterror.setFont(font)
        self.selpatienterror.setStyleSheet("font: 57 10pt \"Montserrat SemiBold\";\n"
"color: rgb(220, 26, 0);")
        self.selpatienterror.setAlignment(QtCore.Qt.AlignCenter)
        self.selpatienterror.setObjectName("selpatienterror")
        self.menuWidget.addWidget(self.apts_pg)
        self.settings_pg = QtWidgets.QWidget()
        self.settings_pg.setObjectName("settings_pg")
        self.Title_3 = QtWidgets.QLabel(self.settings_pg)
        self.Title_3.setGeometry(QtCore.QRect(340, 30, 391, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.Title_3.setFont(font)
        self.Title_3.setStyleSheet("color: rgb(255, 163, 134);\n"
"font: 63 16pt \"Montserrat SemiBold\";")
        self.Title_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_3.setObjectName("Title_3")
        self.label = QtWidgets.QLabel(self.settings_pg)
        self.label.setGeometry(QtCore.QRect(140, 131, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(102, 75, 66);")
        self.label.setObjectName("label")
        self.langsel = QtWidgets.QComboBox(self.settings_pg)
        self.langsel.setGeometry(QtCore.QRect(350, 140, 381, 31))
        self.langsel.setStyleSheet("/* QComboBox */\n"
"QComboBox {\n"
"    background-color: rgb(228, 235, 227);\n"
"    border-radius: 10px;\n"
"    font: 57 9pt \"Montserrat Medium\";\n"
"    padding-left: 11px;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 25px;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    border: 5px solid rgba(255, 255, 255, 0);\n"
"    width: 0;\n"
"    height: 0;\n"
"    border-bottom: none;\n"
"    border-top-color: rgb(255, 163, 134);\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QComboBox::drop-down:hover {\n"
"    background-color: rgb(229, 226, 218);\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"")
        self.langsel.setObjectName("langsel")
        self.langsel.addItem("")
        self.menuWidget.addWidget(self.settings_pg)
        self.horizontalLayout_3.addWidget(self.menuWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.menuWidget.setCurrentIndex(0)
        self.viewWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dr_name.setText(_translate("MainWindow", "Clincian Name"))
        self.dr_desc.setText(_translate("MainWindow", "Clinician Description"))
        self.view_btn.setText(_translate("MainWindow", "     Patient Records"))
        self.add_btn.setText(_translate("MainWindow", "   Add Patient"))
        self.apt_btn.setText(_translate("MainWindow", "     Appointments"))
        self.settings_btn.setText(_translate("MainWindow", "     Settings"))
        self.exit_btn.setText(_translate("MainWindow", "     Logout and Exit"))
        self.name_btn.setText(_translate("MainWindow", "Patient Name Button"))
        self.nopatients.setText(_translate("MainWindow", "No Patients Found"))
        self.profiles_title.setText(_translate("MainWindow", "Select Patient Profile by Clicking Name"))
        self.overview_title.setText(_translate("MainWindow", "{Name}\'s Overview"))
        self.backtoprof_btn.setText(_translate("MainWindow", "Back to Profiles"))
        self.viewrec_btn.setText(_translate("MainWindow", "View Recording History"))
        self.addrec_btn.setText(_translate("MainWindow", "Add New Recording"))
        self.label_40.setText(_translate("MainWindow", "Recordings"))
        self.label_41.setText(_translate("MainWindow", "Recent Progress"))
        self.label_42.setText(_translate("MainWindow", "Session vs Pathology Severity"))
        self.name_ov.setText(_translate("MainWindow", "Name"))
        self.birthday_ov.setText(_translate("MainWindow", "Birthday"))
        self.sex_ov.setText(_translate("MainWindow", "Sex"))
        self.label_46.setText(_translate("MainWindow", "Pitch Period vs MFCC"))
        self.rec_title.setText(_translate("MainWindow", "{Name}\'s Recording History"))
        self.backtoprof_btn_2.setText(_translate("MainWindow", "Back to Profiles"))
        self.loadingrec.setText(_translate("MainWindow", "Loading Recordings...."))
        self.norec.setText(_translate("MainWindow", "No Recordings Found"))
        self.Title_10.setText(_translate("MainWindow", "Recording New Voice Sample"))
        self.startrec_btn.setText(_translate("MainWindow", "  Start Recording   "))
        self.stoprec_btn.setText(_translate("MainWindow", "  Stop Recording    "))
        self.playback_btn.setText(_translate("MainWindow", "  Play Back               "))
        self.redo_btn.setText(_translate("MainWindow", "  Re-Do                      "))
        self.save_btn.setText(_translate("MainWindow", "  Analyze and Save"))
        self.rec_patient.setText(_translate("MainWindow", "Current Patient Selected"))
        self.label_43.setText(_translate("MainWindow", "Date:"))
        self.label_44.setText(_translate("MainWindow", "Patient Name:"))
        self.label_45.setText(_translate("MainWindow", "Notes:"))
        self.rec_date.setText(_translate("MainWindow", "Date"))
        self.label_16.setText(_translate("MainWindow", "Phrase:"))
        self.viewrec_btn_2.setText(_translate("MainWindow", "View Recording History"))
        self.savesuccess.setText(_translate("MainWindow", "Analysis and Save Success"))
        self.savefail.setText(_translate("MainWindow", "Analysis and Save Failed"))
        self.loading.setText(_translate("MainWindow", "Loading..."))
        self.label_6.setText(_translate("MainWindow", "First Name:"))
        self.label_7.setText(_translate("MainWindow", "Email:"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.label_8.setText(_translate("MainWindow", "Birthday:"))
        self.label_5.setText(_translate("MainWindow", "Last Name:"))
        self.createprofile.setText(_translate("MainWindow", "Create Profile"))
        self.Title.setText(_translate("MainWindow", "Create New Patient Profile"))
        self.label_15.setText(_translate("MainWindow", "Sex (F/M):"))
        self.profilesuccess.setText(_translate("MainWindow", "Profile Created Successfully"))
        self.sexdropdown.setItemText(0, _translate("MainWindow", "Female"))
        self.sexdropdown.setItemText(1, _translate("MainWindow", "Male"))
        self.failed_patient.setText(_translate("MainWindow", "Account Creation Failed"))
        self.label_2.setText(_translate("MainWindow", "Peach123 (Default)"))
        self.label_17.setText(_translate("MainWindow", "Upcoming Appointments"))
        item = self.apttable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.apttable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time"))
        item = self.apttable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Patient"))
        item = self.apttable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Note"))
        self.label_21.setText(_translate("MainWindow", "New Appointment"))
        self.label_37.setText(_translate("MainWindow", "Date:"))
        self.label_38.setText(_translate("MainWindow", "Patient Name:"))
        self.patientdropdown.setItemText(0, _translate("MainWindow", "Select Patient"))
        self.booknow_btn.setText(_translate("MainWindow", "Book Now"))
        self.label_39.setText(_translate("MainWindow", "Note:"))
        self.aptsuccess.setText(_translate("MainWindow", "Appointment Booked Successfully"))
        self.selpatienterror.setText(_translate("MainWindow", "Select a Patient"))
        self.Title_3.setText(_translate("MainWindow", "Settings"))
        self.label.setText(_translate("MainWindow", "Language"))
        self.langsel.setItemText(0, _translate("MainWindow", "English"))
import resource_rc
